#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Regenerate src/sprites.rs from assets/sprites/*.png.

Emits the exact RGBA pixel data of the 12 standard SpicyGame sprites as static
Rust arrays so the binary needs no runtime image decoding. The source PNGs are
the byte-for-byte vendored pack files (see assets/PROVENANCE.md for checksums).

Usage: python3 tools/generate_sprites.py
"""
import os

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPRITE_DIR = os.path.join(ROOT, "assets", "sprites")
OUT = os.path.join(ROOT, "src", "sprites.rs")
SIDES = ("White", "Black")
ROLES = ("King", "Queen", "Rook", "Bishop", "Knight", "Pawn")
SIZE = 16
PIXELS = SIZE * SIZE * 4


def rgba(name: str) -> bytes:
    img = Image.open(os.path.join(SPRITE_DIR, name)).convert("RGBA")
    if img.size != (SIZE, SIZE):
        raise SystemExit(f"{name}: expected {SIZE}x{SIZE}, got {img.size}")
    data = img.tobytes()
    if len(data) != PIXELS:
        raise SystemExit(f"{name}: expected {PIXELS} bytes, got {len(data)}")
    return data


def emit_pixels(data: bytes) -> list[str]:
    out = []
    for i in range(0, PIXELS, 16):
        out.append("    " + ", ".join(str(b) for b in data[i:i + 16]) + ",")
    return out


lines: list[str] = []
lines.append("// SPDX-License-Identifier: GPL-3.0-or-later")
lines.append("// @generated by tools/generate_sprites.py — do not edit by hand.")
lines.append("// Exact RGBA pixel data of the 12 standard sprites from the")
lines.append("// Pixel Chess Pieces pack by SpicyGame (CC0). See assets/PROVENANCE.md.")
lines.append("")
lines.append("use shakmaty::{Color as Side, Role};")
lines.append("")
lines.append(f"pub(crate) const SPRITE_SIZE: usize = {SIZE};")
lines.append(f"pub(crate) const SPRITE_BYTES: usize = {PIXELS};")
lines.append("")
for side in SIDES:
    for role in ROLES:
        name = f"{side.lower()}_{role.lower()}.png"
        constname = f"{side.upper()}_{role.upper()}"
        lines.append(f"pub(crate) const {constname}: [u8; {PIXELS}] = [")
        lines.extend(emit_pixels(rgba(name)))
        lines.append("];")
        lines.append("")
lines.append("pub(crate) fn sprite_pixels(side: Side, role: Role) -> &'static [u8; SPRITE_BYTES] {")
lines.append("    match (side, role) {")
for side in SIDES:
    for role in ROLES:
        constname = f"{side.upper()}_{role.upper()}"
        lines.append(f"        (Side::{side}, Role::{role}) => &{constname},")
lines.append("    }")
lines.append("}")

with open(OUT, "w") as f:
    f.write("\n".join(lines) + "\n")
print("wrote", OUT)